{"name": "test_fail3", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail3():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:8: AssertionError"}, "start": 1759909735335, "stop": 1759909735335, "uuid": "b411d562-9c82-4106-aaa5-25e100fb2f5c", "historyId": "3871665697ea3d8351c8bbb21a2393bd", "testCaseId": "3871665697ea3d8351c8bbb21a2393bd", "fullName": "tests.simple.test_fail#test_fail3", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air.local"}, {"name": "thread", "value": "36329-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}], "titlePath": ["tests", "simple", "test_fail.py"]}