{"name": "test_fail4", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail4():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:11: AssertionError"}, "start": 1759909735336, "stop": 1759909735336, "uuid": "6d8298d1-621a-4b74-b768-eaa08146e205", "historyId": "f9f49e04500ac018e8389a41fc795dc7", "testCaseId": "f9f49e04500ac018e8389a41fc795dc7", "fullName": "tests.simple.test_fail#test_fail4", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air.local"}, {"name": "thread", "value": "36329-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}], "titlePath": ["tests", "simple", "test_fail.py"]}