{"name": "test_fail5", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail5():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:14: AssertionError"}, "start": 1759909735337, "stop": 1759909735337, "uuid": "30a59610-b032-4c66-840c-3b92e05be923", "historyId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "testCaseId": "3ed4406b36bfdd2ca409ebda6d8af2cc", "fullName": "tests.simple.test_fail#test_fail5", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air.local"}, {"name": "thread", "value": "36329-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}], "titlePath": ["tests", "simple", "test_fail.py"]}