{"name": "test_fail1", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_fail1():\n>       assert False\nE       assert False\n\ntests/simple/test_fail.py:2: AssertionError"}, "start": 1759909735333, "stop": 1759909735333, "uuid": "25e9887f-5264-4747-93d5-b027fb7aaf98", "historyId": "5980a0f138d2262d80936b48f834090e", "testCaseId": "5980a0f138d2262d80936b48f834090e", "fullName": "tests.simple.test_fail#test_fail1", "labels": [{"name": "parentSuite", "value": "tests.simple"}, {"name": "suite", "value": "test_fail"}, {"name": "host", "value": "MacBook-Air.local"}, {"name": "thread", "value": "36329-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.simple.test_fail"}], "titlePath": ["tests", "simple", "test_fail.py"]}